# Generated by Django 5.2.7 on 2025-11-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bancos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.IntegerField(default=96)),
                ('margem_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_liberado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_parceiro_valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='app_bancos.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='app_usuarios.cliente')),
            ],
        ),
    ]
