# Generated by Django 5.2.7 on 2025-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id_parceiro', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200)),
                ('comissao', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
                ('cidade', models.TextField(max_length=31)),
            ],
        ),
    ]
