# Generated by Django 5.2.7 on 2025-11-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parceiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiros',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='parceiros',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='parceiros',
            name='id_parceiro',
        ),
        migrations.AddField(
            model_name='parceiros',
            name='matricula',
            field=models.CharField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
