# Generated by Django 5.2.7 on 2025-11-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
