"""
Django settings for gocosing project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# carregar .env na raiz do projeto
# localizar raiz do repositório (um nível acima de BASE_DIR atual)
REPO_ROOT = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# obter SECRET_KEY e falhar rapidamente se não existir
SECRET_KEY = 'django-insecure-oc6xc0gu$r1n2bn9$h=bgdi-_in5$_1l6@2+nkt$)1-4g8_f*k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #=====================================================
    # Importante para o funcionamento com o frontend React
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    #=====================================================
    'app_bancos',
    'app_parceiros',
    'app_usuarios',
    'app_emprestimos',
    'app_historico',
    #=====================================================
    # Segurança adicional
    'axes',
    #=====================================================
]

# Autenticação: incluir o backend do django-axes (AxesStandaloneBackend)
# Nota: em django-axes v5.0 o AxesModelBackend foi renomeado para AxesStandaloneBackend
# coloque o backend do axes antes do backend padrão para que ele possa participar
# das tentativas de autenticação/restrição.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
            'rest_framework.authentication.SessionAuthentication',
        ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Configuração do drf-spectacular (geração automática de OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'GoConsig API',
    'DESCRIPTION': 'Documentação automática da API (OpenAPI) gerada por drf-spectacular',
    'VERSION': '1.0.0',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    #=======================================================
    # Segurança adicional com django-axes
    'axes.middleware.AxesMiddleware',
    #=======================================================
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

ROOT_URLCONF = 'goconsig.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [REPO_ROOT / 'frontend-goconsig' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goconsig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    REPO_ROOT / 'frontend-goconsig' / 'dist',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#========================================================================
# Configurações de segurança para produção
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# HTTP Strict Transport Security (HSTS)
#SECURE_HSTS_SECONDS = 31536000  # Um ano
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True
# 
#SECURE_BROWSER_XSS_FILTER = True
#X_CONTENT_TYPE_OPTIONS = 'nosniff'

X_FRAME_OPTIONS = 'DENY'



PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

AXES_FAILURE_LIMIT = 5  # Número máximo de tentativas de login
AXES_COOLOFF_TIME = 1 # Tempo de bloqueio em horas

# Logs
# Diretório para arquivos de log (criado automaticamente se não existir)
LOG_DIR = REPO_ROOT / 'logs'
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    # fallback para BASE_DIR caso não seja possível criar a pasta de logs
    LOG_DIR = BASE_DIR

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'django_security.log'),
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# tempo em segundos (ex.: 3600 = 1 hora)
SESSION_COOKIE_AGE = 3600
# se True o cookie expira ao fechar o navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# se True, cada request renova a expiração (sliding window)
SESSION_SAVE_EVERY_REQUEST = False
#========================================================================
