# Generated by Django 5.2.7 on 2025-11-24 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_parceiros', '0002_remove_parceiros_cidade_remove_parceiros_comissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Parceiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_parceiros.parceiros')),
            ],
        ),
    ]
