# Generated by Django 5.2.7 on 2025-11-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bancos', '0005_banco_delete_bancos'),
        ('app_parceiros', '0002_remove_parceiros_cidade_remove_parceiros_comissao_and_more'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fator_banco', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor_liberado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.IntegerField()),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('Parceiros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='app_parceiros.parceiros')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='app_bancos.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='app_usuarios.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
