# Generated by Django 5.2.7 on 2025-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('codigo_TED', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_banco', models.TextField(max_length=100)),
            ],
        ),
    ]
