# Generated by Django 5.2.7 on 2025-11-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('codigo_banco', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('fator', models.DecimalField(decimal_places=6, max_digits=10)),
                ('comissao_parceiro', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
