# Generated by Django 5.2.7 on 2025-11-23 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='fator_banco',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.023656'), max_digits=10),
        ),
    ]
