# Generated by Django 5.2.7 on 2025-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancos', '0002_bancos_fator_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='fator_banco',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
    ]
