# Generated by Django 5.2.7 on 2025-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancos', '0003_alter_bancos_fator_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='taxa_comissao',
            field=models.IntegerField(default=1),
        ),
    ]
